### ISSUE TITLE
"." search not working

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/fhir-ontology-generator#103]
A search for a code which contains a "." is currently not working.

For example E13.0 finds nothing

**Comment by michael-82** [comment]
There was actually another issue in the [backend](https://github.com/medizininformatik-initiative/feasibility-backend) (or more specifically in the elastic search init script used for the init container).
The curl cmd used to delete the previous indices was wrong, leading to the indices not being correctly updated. This bug is fixed in [PR 385 in the backend](https://github.com/medizininformatik-initiative/feasibility-backend/pull/385) in the file [elastic-init.sh](https://github.com/medizininformatik-initiative/feasibility-backend/commit/d869573288a1c9a9fa6444ec9783a1a585c70aa7#diff-0ec6cf187110751288113921e4064a05a6d333dfe9ce70a9b6e4e8e6e49417a0L22)
As of today there is no release of this version of the backend.
